version: '3.7'

services:
  server:
    build:
      context: ../../
      dockerfile: ./config/docker/Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    command: node dist/server.js
