name: Acceptance Tests

on:
  repository_dispatch:
    types: [run_acceptance]
  # schedule:
  #   #       m h d m dw (minutes, hours, day of month, month, day of week) => run  at 08:00 every day
  #   - cron: 0 8 * * *

jobs:
  acceptance-tests:
    env:
      PREVIOUS_PASSED_TESTS_FILE_PATH: ./previous-passed-tests.json
      ACCEPTANCE_TEST_REGRESSIONS_FILE_PATH: ./test-regressions.json
      GET_PREVIOUS_PASSED_TESTS_URL: ${{ secrets.getPreviousPassedTestsUrl }}
      POST_PREVIOUS_PASSED_TESTS_URL: ${{ secrets.postPreviousPassedTestsUrl }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn
        run: yarn --frozen-lockfile

      - name: Fetch previous passed tests
        run: curl "$GET_PREVIOUS_PASSED_TESTS_URL" > $PREVIOUS_PASSED_TESTS_FILE_PATH

      - name: Run Acceptance Tests
        # It uses the file path env variables set above
        run: ./scripts/test-acceptance.sh || echo "There are failing tests but we only care about regressions which we check for below"

      - name: Persist previous passed tests to track regressions
        run: curl "$POST_PREVIOUS_PASSED_TESTS_URL" --data "$(cat $PREVIOUS_PASSED_TESTS_FILE_PATH)"

      - name: Check if there were regressions
        run: echo -n "[]" | cmp --silent $ACCEPTANCE_TEST_REGRESSIONS_FILE_PATH -

      - name: Store regressions as artifact if there were any
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: Regressions json
          path: ${{ env.ACCEPTANCE_TEST_REGRESSIONS_FILE_PATH }}
