name: Acceptance Tests
'on':
  repository_dispatch:
    types:
      - run_acceptance
  schedule:
    - cron: 0 8 * * *
jobs:
  acceptance-tests:
    env:
      PREVIOUS_PASSED_TESTS_FILE_PATH: /previous-passed-tests.json
      GET_PREVIOUS_PASSED_TESTS_URL: '${{ secrets.getPreviousPassedTestsUrl }}'
      POST_PREVIOUS_PASSED_TESTS_URL: '${{ secrets.postPreviousPassedTestsUrl }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn
        run: yarn --frozen-lockfile
      - name: Fetch previous passed tests
        run: >-
          curl "$GET_PREVIOUS_PASSED_TESTS_URL" >
          $PREVIOUS_PASSED_TESTS_FILE_PATH
      - name: Run Acceptance Tests
        run: ./scripts/test-acceptance.sh
      - name: Persist previous passed tests to track regressions
        run: >-
          curl "$POST_PREVIOUS_PASSED_TESTS_URL" --data "$(cat
          $PREVIOUS_PASSED_TESTS_FILE_PATH)""
