# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn
        run: yarn --frozen-lockfile

      - name: Lint and type check
        run: ./scripts/lint-everything.sh

      - name: Run tests
        run: ./scripts/test-quick.sh

      - name: Run End To End Tests
        run: ./scripts/test-end-to-end.sh

      - name: Check that our custom eslint rules are up to date with source
        run: ./scripts/custom-eslint-rules-are-up-to-date.sh

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1.0.6
